version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d

  customers_service:
    build:
      context: ./customers_service
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=ecommerce
    depends_on:
      - db

  inventory_service:
    build:
      context: ./inventory_service
    ports:
      - "5002:5002"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=ecommerce
    depends_on:
      - db

  sales_service:
    build:
      context: ./sales_service
    ports:
      - "5003:5003"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=ecommerce
    depends_on:
      - db

  reviews_service:
    build:
      context: ./reviews_service
    ports:
      - "5004:5004"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=ecommerce
    depends_on:
      - db